name: Publish Python 🐍 distributions 📦 to PyPI

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update version
        run: python get_latest_version.py
      - name: Install deployment dependencies
        if: github.event.pull_request.merged == true
        run: |
          pip install twine
          pip install pexpect
      - name: Package module
        if: github.event.pull_request.merged == true
        run: python setup.py sdist
      - name: Deploy to PyPI
        if: github.event.pull_request.merged == true
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
